import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage()
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' })
await page.locator('#login-email').fill('aswin@gmail.com')
await page.locator('#login-password').fill('aswin@')
await page.locator('button.login-submit').click()
await page.waitForTimeout(4000)
console.log('URL:', page.url())
const err = await page.locator('.login-error').textContent().catch(() => '(no element)')
console.log('login-error:', err)
await browser.close()
