import { chromium } from 'playwright'
const BASE = 'http://localhost:5173'
const browser = await chromium.launch()
const page = await browser.newPage()
await page.goto(BASE, { waitUntil: 'networkidle' })
await page.locator('#login-email').fill('aravidhan@company.com')
await page.locator('#login-password').fill('aravidhan@')
await page.locator('button.login-submit').click()
await page.waitForFunction(() => location.pathname !== '/', null, { timeout: 15000 })
await page.waitForLoadState('networkidle')
await page.waitForTimeout(1500)
const titleCount = await page.locator('.card-title').count()
const titles = await page.locator('.card-title').allInnerTexts()
console.log('titles:', titles)
const card = page.locator('.card:has(.card-title:text-is("My team\'s exits"))')
console.log('card count:', await card.count())
console.log('row count inside:', await card.locator('.row').count())
console.log('full card html len:', (await card.innerHTML().catch(e=>String(e))).length)
await browser.close()
