import { svc, casesFor, j } from './lib.mjs'
const db = svc()
const { data: p } = await db.from('profiles').select('id, employee_id, full_name, email, department, role, out_of_office').eq('employee_id','Emp031').maybeSingle()
console.log('Emp031 profile:', j(p))
console.log('existing cases for Emp031:', j(await casesFor('Emp031')))
const { data: mgr } = await db.from('profiles').select('id, full_name, email').eq('role','manager').limit(1).single()
const { data: hr } = await db.from('profiles').select('id, full_name, email').eq('role','hr').limit(1).single()
console.log('manager pick:', j(mgr)); console.log('hr pick:', j(hr))
const { data: allm } = await db.from('profiles').select('id, full_name, email, role, out_of_office, department').in('role',['manager','hr','it','finance'])
console.log('staff:', j(allm))
