import { chromium } from 'playwright'
const BASE = 'http://localhost:5173'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage()
await page.goto(BASE, { waitUntil: 'networkidle' })
await page.fill('#login-email', 'aravidhan@company.com')
await page.fill('#login-password', 'aravidhan@')
await page.click('.login-submit')
await page.waitForURL(/\/manager/, { timeout: 10000 })
await page.goto(`${BASE}/manager/kt-approvals`, { waitUntil: 'networkidle' })
const row = page.locator('.row', { hasText: 'failure path' })
await row.locator('button', { hasText: 'Reject' }).click()
await page.waitForTimeout(2000)
const errP = row.locator('p.sub.c-danger')
console.log('error paragraph count:', await errP.count())
console.log('error paragraph text:', await errP.first().textContent().catch(() => '(none)'))
await browser.close()
