import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage()
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' })
await page.fill('#login-email', 'aravidhan@company.com')
await page.fill('#login-password', 'aravidhan@')
await page.click('.login-submit')
await page.waitForURL(/\/manager/, { timeout: 10000 })
await page.goto('http://localhost:5173/manager/kt-approvals', { waitUntil: 'networkidle' })
const html = await page.content()
const idx = html.toLowerCase().indexOf('reject')
console.log(html.slice(Math.max(0, idx - 200), idx + 200))
await browser.close()
